name: Trigger auto deployment for ragpgpy-gy6v6i7cfj3-ca

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ragpgpy-gy6v6i7cfj3-ca-AutoDeployTrigger-465cfe41-121a-4b89-9fd1-1ef18fd00fb9.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.RAGPGPYGY6V6I7CFJ3CA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.RAGPGPYGY6V6I7CFJ3CA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.RAGPGPYGY6V6I7CFJ3CA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ragpgpygy6v6i7cfj3lyregistry.azurecr.io
          registryUsername: ${{ secrets.RAGPGPYGY6V6I7CFJ3CA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RAGPGPYGY6V6I7CFJ3CA_REGISTRY_PASSWORD }}
          containerAppName: ragpgpy-gy6v6i7cfj3-ca
          resourceGroup: ResourceGroup1
          imageToBuild: ragpgpygy6v6i7cfj3lyregistry.azurecr.io/ragpgpy-gy6v6i7cfj3-ca:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


